# Generated by Django 5.2.3 on 2025-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Токен сброса пароля"),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_created",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время создания токена сброса"),
        ),
    ]
