# Generated by Django 5.2.3 on 2025-07-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_reset_token_user_reset_token_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_view_all_users", "Можно просматривать всех пользователей")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
