# Generated by Django 5.2.3 on 2025-07-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
    ]
