# Generated by Django 5.2.3 on 2025-07-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": (("view_all_clients", "Может просматривать всех получателей"),),
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
