# Generated by Django 5.2.3 on 2025-07-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings_message", "0002_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_see_all_messages", "Можно видеть все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
