# Generated by Django 5.2.3 on 2025-07-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings_message", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptSend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        default="success",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Ответ сервера"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings_message.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
            },
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата старта рассылки")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("finished", "Завершена")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("clients", models.ManyToManyField(blank=True, to="clients.client", verbose_name="Получатели")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings_message.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
