# Generated by Django 5.2.3 on 2025-07-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings", "0001_initial"),
        ("mailings_message", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingList",
            new_name="Mailings",
        ),
    ]
