# Generated by Django 5.2.3 on 2025-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_rename_mailinglist_mailings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptsend",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Статус"),
        ),
    ]
