# Generated by Django 5.2.3 on 2025-07-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_mailings_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attemptsend",
            name="message",
        ),
        migrations.AddField(
            model_name="attemptsend",
            name="mailing",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to="mailings.mailings", verbose_name="Рассылка"
            ),
            preserve_default=False,
        ),
    ]
