# Generated by Django 5.2.3 on 2025-07-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings", "0005_remove_attemptsend_message_attemptsend_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptsend",
            name="email",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="clients.client", verbose_name="Получатель"
            ),
            preserve_default=False,
        ),
    ]
