# Generated by Django 5.2.3 on 2025-07-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings", "0006_attemptsend_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptsend",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
                verbose_name="Получатель",
            ),
        ),
    ]
