# Generated by Django 5.2.3 on 2025-07-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0008_attemptsend_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attemptsend",
            name="owner",
        ),
    ]
