# Generated by Django 5.2.3 on 2025-07-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0009_remove_attemptsend_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailings",
            options={
                "permissions": [("can_stoped", "Может остановить рассылку")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
